#!/bin/sh
export CUDA_ROOT=/usr/local/cuda-9.0
ORIGINAL_LD_LIBRARY_PATH=$LD_LIBRARY_PATH
ORIGINAL_NUMBAPRO_NVVM=$NUMBAPRO_NVVM
ORIGINAL_NUMPAPRO_LIBDEVICE=$NUMBAPRO_LIBDEVICE
export LD_LIBRARY_PATH=$CUDA_ROOT/lib64:$CUDA_ROOT/extras/CUPTI/lib64:$LD_LIBRARY_PATH
export NUMBAPRO_NVVM=$CUDA_ROOT/nvvm/lib64/libnvvm.so
export NUMBAPRO_LIBDEVICE=$CUDA_ROOT/nvvm/libdevice/
ORIGINAL_PATH=$PATH
export PATH=$CUDA_ROOT/bin:$PATH
